# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Change Validation
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Check License
        run: |
          go install github.com/google/addlicense@latest
          addlicense -c "The Tektite Authors" -check -ignore "**/*.yml" -ignore "**/*.xml" . > /dev/null ||
          (
          addlicense -c "The Tektite Authors" -check -v -ignore "**/*.yml" -ignore "**/*.xml" . |
          xargs -I {} echo -e "\e[01;31mERROR\t\e[0mMissing license header in file: {}"; echo -e "
          \e[01;04;32mHOW TO FIX:\e[0m
          
          Make sure the files listed above include the same license header as the rest of the source code files or use the following command to add the license header
          
           go install github.com/google/addlicense@latest
           addlicense -c 'The Tektite Authors' -ignore '**/*.yml' -ignore '**/*.xml' .
          " && exit 1 
          )
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_API_VERSION: 1.43
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: go build -v ./...
  run-unit-tests:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_API_VERSION: 1.43
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y etcd-server default-jre
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Run Unit Tests
        run: gotestsum -f github-actions -- -race -count=1 -p=1 -timeout 10m -failfast ./...
  run-integration-tests:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_API_VERSION: 1.43
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y etcd-server default-jre
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Run Integration Tests
        run: gotestsum -f github-actions -- -race -count=1 -p=1 -timeout 10m -failfast -tags=integration ./integration/...
